### ISSUE TITLE
Unity 4.0 don't work with AutoMapper.Unity

### ISSUE THREAD

**Issue by JarJarBinkz** [srogovtsev/AutoMapper.Unity#3]
I use your AutoMapper.Unity v2.0.7 Nuget-package with Unity v3.5.1404 and AutoMapper v4.1.1.

I now want to update Unity to the current version 4.0.1.

Inside the App.Config (session assemblyBinding = > dependentAssembly) I can't configure Unity v4.0.1 because the assembysigningkey was changed.

Could you create a new NuGet-package with Unity v4.0.1 reference?

**Comment by srogovtsev** [comment]
I will look into it around next week.

**Comment by JarJarBinkz** [comment]
Thank you

**Comment by srogovtsev** [comment]
Sorry it took so long. Version [4.0.12](https://www.nuget.org/packages/AutoMapper.Unity/4.0.12) is up for you to try.

**Comment by JarJarBinkz** [comment]
It works just fine. Thanks much.
