### ISSUE TITLE
Update to AutoMapper 4.2.0

### ISSUE THREAD

**Issue by HawkMG** [srogovtsev/AutoMapper.Unity#4]
Hi,
are you planning an update to AutoMapper 4.2.0? And if so, when?

Thx!

Andreas

**Comment by srogovtsev** [comment]
Is there any particular reason why you can't just use AutoMapper 4.2 with this package?

**Comment by HawkMG** [comment]
Hi,

in AutoMapper 4.1.1 there are constructores for MappingEngine:

```
public MappingEngine(IConfigurationProvider configurationProvider)
      : this(configurationProvider, MappingEngine.DictionaryFactory.CreateDictionary<TypePair, IObjectMapper>(), MappingEngine.DictionaryFactory.CreateDictionary<ExpressionRequest, LambdaExpression>(), configurationProvider.ServiceCtor)
    {
    }
```

```
public MappingEngine(IConfigurationProvider configurationProvider, IDictionary<TypePair, IObjectMapper> objectMapperCache, IDictionary<ExpressionRequest, LambdaExpression> expressionCache, Func<Type, object> serviceCtor)
    {
     // Some Code
    }
```

In AutoMapper 4.2.0 there is only one constructor

```
public MappingEngine(IConfigurationProvider configurationProvider, IMapper mapper)
    {
      // Some code
    }
```

Now, i´ll get an Exception when using your RegisterMapper method

> The type AutoMapper.MappingEngine does not have a constructor that takes the parameters (IConfigurationProvider)


You are injection one constructor parameter in the RegisterMapper Method:

```
...
....
UnityContainerExtensions.RegisterType<IMappingEngine, MappingEngine>(container, (LifetimeManager) new ContainerControlledLifetimeManager(), new InjectionMember[1]
      {
        (InjectionMember) new InjectionConstructor(new object[1]
        {
          (object) typeof (IConfigurationProvider)
        })
      });
....
....

```

Thx!

Andreas

**Comment by srogovtsev** [comment]
Okay, I'll try to fix it. Are you using Unity 3 or Unity 4?

**Comment by HawkMG** [comment]
Hi,

great! Thx!

i´m using Unity 4.0.1

**Comment by srogovtsev** [comment]
So you're using [4.0.12 package](https://www.nuget.org/packages/AutoMapper.Unity/4.0.12)?

**Comment by HawkMG** [comment]
Hi,

yes! I´m using 4.0.12!

**Comment by srogovtsev** [comment]
[5.0.16](https://www.nuget.org/packages/AutoMapper.Unity/5.0.16) is up for you to try.

**Comment by HawkMG** [comment]
Thx for the quick help!

I will test it on Monday!

**Comment by HawkMG** [comment]
Hi!

Seems to work perfectly :-)!

Thx!
